### ISSUE TITLE
" `display': undefined method `session' for nil:NilClass" running correlation 

### ISSUE THREAD

**Issue by tansaku** [SciRuby/statsample#46]
Hi there,

I'm trying to create a correlation matrix using the example here:

http://nbviewer.ipython.org/github/SciRuby/sciruby-notebooks/blob/master/Statistics/Correlation%20Matrix%20with%20daru%20and%20statsample.ipynb

I've got iruby installed, ipython, jupyter-console all installed.  I can run iruby from the command line with no errors.  I'm trying to run the above example from a file like so:

```
$ ruby lib/correlation.rb 
/Users/tansaku/.rvm/gems/ruby-2.2.2/gems/iruby-0.2.7/lib/iruby/utils.rb:8:in `display': undefined method `session' for nil:NilClass (NoMethodError)
	from lib/correlation.rb:34:in `block in <main>'
```

and I'm not sure what to do with the above error that corresponds to this line of code: ```IRuby.display ds.head```

Any ideas?  Should I be working through the IRuby console?

Many thanks in advance

**Comment by tansaku** [comment]
follow up question on this.  I've switched over to pp to just dump the data, and I'm getting a load of nils in my correlation matrix which I don't understand:

```
→ ruby lib/correlation.rb 
== DataFrame ==

#<Daru::DataFrame:70364945937240 @name = 2cec4fef-c7b6-4a55-9481-04966136189d @size = 10>
           coverall_c days_to_of reek_warni rspec_fail rspec_test rubocop_of 
         0         99        207          1          0         13          6 
         1         95        179          4          0          9          2 
         2         99        298          1          0         12         10 
         3         99        298          1          0         15          0 
         4         94        298          3          0          0         31 
         5         97        298          3          0         15         12 
         6         99        298          0          0         12         17 
         7         94        298          1          0          0          4 
         8        100        298          0          0         19         14 
         9        100        298          1          0         16          2 


== Correlation Matrix ==
Matrix[[1.0, 0.10414115946373498, nil, nil, nil, nil], [0.10414115946373498, 1.0, nil, nil, nil, nil], [nil, nil, 1.0, nil, nil, nil], [nil, nil, nil, 1.0, nil, nil], [nil, nil, nil, nil, 1.0, nil], [nil, nil, nil, nil, nil, 1.0]]
Analysis 2015-10-25 18:40:21 +0000
```

Any ideas why?  Do I need to normalize all the data or something?

**Comment by tansaku** [comment]
looks like it was normalization that was required ...
